# Generated by Django 4.0.4 on 2022-05-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pw_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True)),
                ('product', models.ManyToManyField(to='pw_app.product')),
            ],
        ),
    ]
