# Generated by Django 4.0.4 on 2022-05-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pw_app', '0002_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='warehouse',
            field=models.ManyToManyField(to='pw_app.warehouse'),
        ),
    ]
