# Generated by Django 4.0.4 on 2022-05-18 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pw_app', '0003_shipment_warehouse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
