# Generated by Django 4.0.4 on 2022-05-19 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pw_app', '0005_shipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='shipment',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pw_app.product'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='warehouses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pw_app.warehouse'),
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='product',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='product',
            field=models.ManyToManyField(to='pw_app.product'),
        ),
    ]
